[package]
name = "milagro-crypto"
version = "0.1.0"
authors = ["Sergej Pupykin <sergej.pupykin@dsr-company.com>"]
build="build.rs"
license="APACHE2"
description="milagro-crypto-c Rust wrappers. (c) Sovrin Fundation"

[build-dependencies]
pkg-config = "*"

[dependencies]
libc = "^0"
